export enum InternshipStatus {
  ACTIVITY_PLAN_PENDING = ("ACTIVITY_PLAN_PENDING"),
  ACTIVITY_PLAN_SENT = ("ACTIVITY_PLAN_SENT"),
  IN_PROGRESS = ("IN_PROGRESS"),
  REALIZATION_TERM_ACCEPTED = ("REALIZATION_TERM_ACCEPTED"),
  FINISHED = ("FINISHED")
}