export enum InternshipType {
  REQUIRED_OR_NOT = ("REQUIRED_OR_NOT"),
  REQUIRED = ("REQUIRED"),
  NOT_REQUIRED =  ("NOT_REQUIRED"),
  PROFESSIONAL_VALIDATION = ("PROFESSIONAL_VALIDATION"),
  PROJECT_EQUIVALENCE = ("PROJECT_EQUIVALENCE")
} 