export enum ReportStatus {
  DRAFT_PENDING = ("DRAFT_PENDING"),
  DRAFT_SENT = ("DRAFT_SENT"),
  FINAL_PENDING = ("FINAL_PENDING"),
  FINAL_SENT = ("FINAL_SENT"),
  FINAL_ACCEPTED = ("FINAL_ACCEPTED"),
}